### ISSUE TITLE
Roboten blir drept i steden for å bli stoppet av en vegg

### ISSUE THREAD

**Issue by EpicKnarvik97** [inf112-v20/Fiasko#38]
**Beskriv problemet**
Når en robot er på vei ut av brettet, men skulle bli stoppet av en vegg, blir den drept i stedet for stoppet.

**For å reprodusere problemet**
Steg for reprodusering:
1. Beveg en robot ut av brettet et sted der det er en vegg

**Forventet oppførsel**
Roboten skulle bli stoppet av veggen, ikke drept.

**Løsning**
Rekkefølgen på robotMoveIsStoppedByWall og killRobotIfGoesOutsideMap må byttes om. Da må det også sjekkes at den nye posisjonen er gyldig i robotMoveIsStoppedByWall før den brukes.

**Comment by torlunjen** [comment]
Jeg har testet koden før og etter mine endringer for denne bugen. Bugen var der i den tidligere koden også.

**Comment by EpicKnarvik97** [comment]
> 
> 
> Jeg har testet koden før og etter mine endringer for denne bugen. Bugen var der i den tidligere koden også.

Løsningen står der, så du får lov til å fikse det.
