### ISSUE TITLE
En robot skal kun registrere besøk på ett flagg per runde

### ISSUE THREAD

**Issue by torlunjen** [inf112-v20/Fiasko#62]
Sånn som det står nå kan en robot registrere besøk på ett flagg per fase.

Korrekt oppførsel er:
En robot skal ikke kunne registrere mer enn ett flagg per runde, men i hvilken som helst av fasene i en runde.

**Comment by EpicKnarvik97** [comment]
Akkurat nå blir setHasTouchedFlagThisTurn kjørt på en kopi av en robot. Derfor kan en robot fortsatt besøke et flagg hver fase. I tillegg bør ikke roboter hentes ut fra getAliveRobots. Det må lages hjelpemetoder i Board som tar seg av det istedenfor.
