### ISSUE TITLE
Testing av faser

### ISSUE THREAD

**Issue by EpicKnarvik97** [inf112-v20/Fiasko#67]
Siden faser kan testes automatisk, bør dette gjøres slik at vi kan stole på at faser fungerer.
Ting som må testes:
Transporbånd:
- Om to roboter står på transportbånd som peker mot samme tile, skal ingen av dem flytte seg.
- Om en robot står på et transporbånd som peker mot et hull eller enden av kartet, skal den flytte seg.
- Obs: Om en robot står på et transporbånd som peker mot et hull og en annen robot står på et transporbånd som peker mot samme hull, skal ingen av dem flytte seg.
- En robot som står på et transportbånd bak en robot som ikke kan flytte seg skal ikke flyttes.
- En robot som står på et transportbånd bak en robot som kan flytte seg skal flyttes.
- En robot som står på et transportbånd som peker mot en vegg skal ikke flytte seg.
- En kjede av roboter som står i en 2x2 ring av transportbånd skal ikke skape en evig loop.
Kjøring av programmeringskort
- Programmeringskort utfører forventet handling i forventet rekkefølge
Avfyring av lasere
- En robot tar korrekt antall skade etter den er truffet av en laser
Registering av flagg
- Etter at en robot har besøkt første flagg skal den ha registrert det.
- En robot som starter med å besøke andre flagg skal ikke ha registrert noen flagg.
- En robot som har registrert første flagg skal kunne registrere andre flagg.
Rotering av tannhjul
- Retningen til roboten har endret seg som forventet etter at tannhjulet har bevegd seg.
Utføre en Action?
Vinning av spillet
- En spiller som har besøkt alle flagg må markeres som vinner

**Comment by GabrielMagnus** [comment]
Lage test for å sjekke at en robot blir blokket av en vegg som skal hindre transportbånd å flytte roboten av brettet
